# opsgenie Exporter Workflow
# This workflow responsible for running opsgenie exporter.
# api_token: The API token used to authenticate requests to Opsgenie REST API. To generate an API token, see the <a target="_blank" href="https://support.atlassian.com/opsgenie/docs/api-key-management">Opsgenie documentation</a>.
# api_url: Opsgenie can have two different API URLs, and the one you need depends on where your Opgenie instance is located. Customers in the EU region should use https://api.eu.opsgenie.com whereas customers in the US region should use https://api.opsgenie.com. If the OpsGenie API URL is not provided, the default value is https://api.opsgenie.com

on:
    workflow_dispatch:
    schedule:
        - cron: '0 */1 * * *' # Determines the scheduled interval for this workflow. This example runs every hour.

jobs:
    run-integration:
        runs-on: ubuntu-latest
		timeout-minutes: 30 # Set a time limit for the job
		
        steps:
            - name: Run opsgenie Integration
              uses: port-labs/ocean-sail@v1
              with:
                type: opsgenie
                port_client_id: ${{ secrets.PORT_CLIENT_ID }}
                port_client_secret: ${{ secrets.PORT_CLIENT_SECRET }}
                port_base_url: "https://api.getport.io"
                config: |
                    api_token: ${{ secrets.apiToken }}
                    api_url: https://api.opsgenie.com
